name: Build

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches:
    - main
    - features/*

env:
  DOTNET_ROLL_FORWARD: Major

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure environment
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Build the project
      - name: Call build script
        run: ./build.sh

      # Prepare artifacts(s) [WIP]
      - name: Get solution name
        id: get-solution-name
        run: echo "::set-output name=SOLUTION_NAME::$(basename $(find ./dist -type f -iname "*"))
      - name: Print out SOLUTION_NAME variable
        run: echo "SOLUTION_NAME = $SOLUTION_NAME"
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ steps.get-solution-name.outputs.SOLUTION_NAME }}
      #     path: ./dist/${{ steps.get-solution-name.outputs.SOLUTION_NAME }}
      #     retention-days: 15


      # Prepare artifact(s)
      # - Create an arbitrary file in the root of the dist directory.
      #   This is to avoid the artifacts zip auto extracting when double clicked.
      - run: echo "${{ github.server_url }}/${{ github.repository }}" > ./dist/repo-url.txt
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}__extract_this_zip
          path: ./dist/*
          retention-days: 15
